---
- hosts: all
  gather_facts: true

- hosts: controllers
  gather_facts: True
  become: true
  roles:
    - controller

- hosts: workers
  gather_facts: True
  become: true
  roles:
    - worker

- hosts: loadbalancers
  gather_facts: True
  become: true
  roles:
    - loadbalancer