---
#- hosts: all
#  gather_facts: true
#  roles:
#    - common
#  environment:
#    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
#    GOPATH: "{{ ansible_env.HOME }}/go"

- hosts: controllers
  gather_facts: True
  roles:
    - controller
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
    GOPATH: "{{ ansible_env.HOME }}/go"

- hosts: workers
  gather_facts: True
  roles:
    - worker
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
    GOPATH: "{{ ansible_env.HOME }}/go"

- hosts: loadbalancers
  gather_facts: True
  roles:
    - loadbalancer
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
    GOPATH: "{{ ansible_env.HOME }}/go"