# -*- mode: ruby -*-
# vi: set ft=ruby :

controllers = []
workers = []
loadbalancers = []

Vagrant.configure("2") do |config|
  # controllers
  (1..3).each do |machine|
    config.vm.define "kubes-controller#{machine}" do |node|
      node.vm.box = "ubuntu/precise64"
      node.vm.network "private_network", ip: "10.0.0.#{machine}"
      node.vm.memory = 1280

      controllers << "kubes-controller#{machine}"
    end
  end

  # workers
  (1..3).each do |machine|
    config.vm.define "kubes-worker#{machine}" do |node|
      node.vm.box = "ubuntu/precise64"
      node.vm.network "private_network", ip: "10.0.0.1#{machine}"
      node.vm.memory = 2048

      workers << "kubes-worker#{machine}"
    end
  end

  # loadbalancer
  config.vm.define "kubes-loadbalancer" do |node|
    node.vm.box = "ubuntu/precise64"
    node.vm.network "private_network", ip: "10.0.0.100"

    loadbalancers << "kubes-loadbalancer"
  end
end

config.vm.provision "ansible" do |ansible|
  ansible.verbose = "v"
  ansible.playbook = "playbook.yml"
  ansible.groups = {
      "controllers" => controllers,
      "workers" => workers,
      "loadbalancers" => loadbalancers
  }
end