---
- name: reload etcd
  command: systemctl daemon-reload
  become: true
  notify:
    - restart etcd

- name: restart etcd
  service:
    name: etcd
    state: restarted
  become: true

- name: reload apiserver
  command: systemctl daemon-reload
  become: true
  notify:
    - restart etcd

- name: restart apiserver
  service:
    name: apiserver
    state: restarted
  become: true