---
- name: create kube-apiserver-to-kubelet role file
  copy:
    content: |
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRole
      metadata:
        annotations:
          rbac.authorization.kubernetes.io/autoupdate: "true"
        labels:
          kubernetes.io/bootstrapping: rbac-defaults
        name: system:kube-apiserver-to-kubelet
      rules:
        - apiGroups:
            - ""
          resources:
            - nodes/proxy
            - nodes/stats
            - nodes/log
            - nodes/spec
            - nodes/metrics
          verbs:
            - "*"
    dest: "{{ ansible_env.HOME }}/.kube/kube-apiserver-to-kubelet"

- name: apply kube-apiserver-to-kubelet role
  command: "kubectl apply -f {{ ansible_env.HOME }}/.kube/kube-apiserver-to-kubelet"

- name: create kube-apiserver-to-kubelet bind to kubernetes user file
  copy:
    content: |
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRoleBinding
      metadata:
        name: system:kube-apiserver
        namespace: ""
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:kube-apiserver-to-kubelet
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: kubernetes
    dest: "{{ ansible_env.HOME }}/.kube/bind-kube-apiserver-to-kubelet-to-kubernetes"

- name: bind kube-apiserver-to-kubelet role to kubernetes user
  command: "kubectl apply -f {{ ansible_env.HOME }}/.kube/bind-kube-apiserver-to-kubelet-to-kubernetes"