---
####
#
# worker
#
####
- name: kubectl kubelet set cluster
  command: >
    bash -c
    "kubectl config set-cluster kubernetes-the-hard-way
    --certificate-authority=/etc/ssl/certs/ca.pem
    --embed-certs=true
    --server=https://{{ public_ip }}:6443
    --kubeconfig={{ ansible_env.HOME }}/.kube/{{ ansible_nodename }}.kubeconfig"

- name: kubectl kubelet set credentials
  command: >
    bash -c
    "kubectl config set-credentials system:node:{{ ansible_nodename }}
    --client-certificate=/etc/ssl/certs/{{ ansible_nodename }}.pem
    --client-key=/etc/ssl/certs/{{ ansible_nodename }}-key.pem
    --embed-certs=true
    --kubeconfig={{ ansible_env.HOME }}/.kube/{{ ansible_nodename }}.kubeconfig"

- name: kubectl kubelet set context
  command: >
    bash -c
    "kubectl config set-context default
    --cluster=kubernetes-the-hard-way
    --user=system:node:{{ ansible_nodename }}
    --kubeconfig={{ ansible_env.HOME }}/.kube/{{ ansible_nodename }}.kubeconfig"


####
#
# kube-proxy
#
####
- name: kubectl kube-proxy set cluster
  command: >
    bash -c
    "kubectl config set-cluster kubernetes-the-hard-way
    --certificate-authority=/etc/ssl/certs/ca.pem
    --embed-certs=true
    --server=https://{{ public_ip }}:6443
    --kubeconfig={{ ansible_env.HOME }}/.kube/kube-proxy.kubeconfig"

- name: kubectl kube-proxy set credentials
  command: >
    bash -c
    "kubectl config set-credentials kube-proxy
    --client-certificate=/etc/ssl/certs/kube-proxy.pem
    --client-key=/etc/ssl/certs/kube-proxy-key.pem
    --embed-certs=true
    --kubeconfig={{ ansible_env.HOME }}/.kube/kube-proxy.kubeconfig"

- name: kubectl kube-proxy set context
  command: >
    bash -c
    "kubectl config set-context default
    --cluster=kubernetes-the-hard-way
    --user=kube-proxy
    --kubeconfig={{ ansible_env.HOME }}/.kube/kube-proxy.kubeconfig"