- name: configure certs
  include_tasks: configure_certs.yml

- name: configure kubectl
  include_tasks: configure_kubectl.yml

- name: set kubectl worker context
  command: "kubectl config use-context default --kubeconfig={{ ansible_env.HOME }}/.kube/{{ ansible_nodename }}.kubeconfig"

- name: set kubectl kube-proxy context
  command: "kubectl config use-context default --kubeconfig={{ ansible_env.HOME }}/.kube/kube-proxy.kubeconfig"